### ISSUE TITLE
broken API tests

### ISSUE THREAD

**Issue by jduss4** [open-oni/open-oni#353]
There are two failing tests:

- test_issue_json
- test_page_json

From a glance it looks like it's related to IIIF metadata sent back with the requests which have `info.json` tacked onto the end of the URL.  If this is expected then we should update the tests, otherwise, look into the response generated by the app.

**Comment by jduss4** [comment]
```
======================================================================
FAIL: test_issue_json (core.tests.test_api.ApiTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/openoni/core/tests/test_api.py", line 110, in test_issue_json
    u'label': u'issue order'}]})
AssertionError: {u'@context': u'http://iiif.io/api/presentation/2/context.json', u'label': u'New [truncated]... != {u'@context': u'http://iiif.io/api/presentation/2/context.json', u'sequences': [ [truncated]...
  {u'@context': u'http://iiif.io/api/presentation/2/context.json',
   u'@id': u'https://oni.example.com/lccn/sn83030214/1898-01-01/ed-1.json',
   u'@type': u'sc:Manifest',
   u'label': u'New-York tribune. [1898-01-01]',
-  u'sequences': [{u'@type': u'sc:Sequence',
+  u'sequences': [{u'@id': u'normal',
+                  u'@type': u'sc:Sequence',
-                  u'canvases': [{u'@id': u'https://oni.example.com/images/tile/batch_curiv_ahwahnee_ver01%2Fdata%2Fsn83030214%2F00175037652%2F1898010101%2F0005.jp2',
+                  u'canvases': [{u'@id': u'https://oni.example.com/images/tile/batch_curiv_ahwahnee_ver01%2Fdata%2Fsn83030214%2F00175037652%2F1898010101%2F0005.jp2/info.json',
?                                                                                                                                                                   ++++++++++

                                  u'@type': u'sc:Canvas',
                                  u'height': 8677,
-                                 u'images': [{u'@id': u'https://oni.example.com/images/tile/batch_curiv_ahwahnee_ver01%2Fdata%2Fsn83030214%2F00175037652%2F1898010101%2F0005.jp2',
+                                 u'images': [{u'@id': u'https://oni.example.com/images/tile/batch_curiv_ahwahnee_ver01%2Fdata%2Fsn83030214%2F00175037652%2F1898010101%2F0005.jp2/info.json',
?                                                                                                                                                                                ++++++++++

                                               u'@type': u'oa:Annotation',
                                               u'motivation': u'sc:painting',
-                                              u'on': u'https://oni.example.com/images/tile/batch_curiv_ahwahnee_ver01%2Fdata%2Fsn83030214%2F00175037652%2F1898010101%2F0005.jp2',
                                               u'rendering': [{u'@id': u'https://oni.example.com/lccn/sn83030214/1898-01-01/ed-1/seq-1.pdf',
                                                               u'format': u'application/pdf'},
                                                              {u'@id': u'https://oni.example.com/lccn/sn83030214/1898-01-01/ed-1/seq-1.jp2',
                                                               u'format': u'image/jp2'},
                                                              {u'@id': u'https://oni.example.com/lccn/sn83030214/1898-01-01/ed-1/seq-1/',
                                                               u'format': u'text/html'}],
-                                              u'resource': {u'@id': u'https://oni.example.com/images/tile/batch_curiv_ahwahnee_ver01%2Fdata%2Fsn83030214%2F00175037652%2F1898010101%2F0005.jp2',
+                                              u'resource': {u'@id': u'https://oni.example.com/images/tile/batch_curiv_ahwahnee_ver01%2Fdata%2Fsn83030214%2F00175037652%2F1898010101%2F0005.jp2/info.json',
?                                                                                                                                                                                              ++++++++++

                                                             u'@type': u'dctypes:Image',
                                                             u'format': u'image/jpeg',
                                                             u'height': 8677,
                                                             u'service': {u'@context': u'http://iiif.io/api/image/2/context.json',
-                                                                         u'@id': u'https://oni.example.com/images/tile/batch_curiv_ahwahnee_ver01%2Fdata%2Fsn83030214%2F00175037652%2F1898010101%2F0005.jp2',
+                                                                         u'@id': u'https://oni.example.com/images/tile/batch_curiv_ahwahnee_ver01%2Fdata%2Fsn83030214%2F00175037652%2F1898010101%2F0005.jp2/info.json',
?                                                                                                                                                                                                           ++++++++++

                                                                          u'profile': u'http://iiif.io/api/image/2/level0.json'},
                                                             u'width': 6394},
                                               u'seeAlso': [{u'@id': u'https://oni.example.com/lccn/sn83030214/1898-01-01/ed-1/seq-1/ocr.xml',
                                                             u'format': u'text/xml'}]}],
                                  u'label': u'1',
                                  u'thumbnail': u'https://oni.example.com/images/resize/batch_curiv_ahwahnee_ver01%2Fdata%2Fsn83030214%2F00175037652%2F1898010101%2F0005.jp2/full/240,/0/default.jpg',
                                  u'width': 6394}],
                   u'label': u'issue order'}]}

======================================================================
FAIL: test_page_json (core.tests.test_api.ApiTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/openoni/core/tests/test_api.py", line 142, in test_page_json
    u'width': 6394})
AssertionError: {u'thumbnail': u'https://oni.example.com/images/resize/batch_curiv_ahwahnee_ver0 [truncated]... != {u'label': u'1', u'width': 6394, u'@type': u'sc:Canvas', u'images': [{u'motivati [truncated]...
- {u'@id': u'https://oni.example.com/images/tile/batch_curiv_ahwahnee_ver01%2Fdata%2Fsn83030214%2F00175037652%2F1898010101%2F0005.jp2',
+ {u'@id': u'https://oni.example.com/images/tile/batch_curiv_ahwahnee_ver01%2Fdata%2Fsn83030214%2F00175037652%2F1898010101%2F0005.jp2/info.json',
?                                                                                                                                    ++++++++++

   u'@type': u'sc:Canvas',
   u'height': 8677,
-  u'images': [{u'@id': u'https://oni.example.com/images/tile/batch_curiv_ahwahnee_ver01%2Fdata%2Fsn83030214%2F00175037652%2F1898010101%2F0005.jp2',
+  u'images': [{u'@id': u'https://oni.example.com/images/tile/batch_curiv_ahwahnee_ver01%2Fdata%2Fsn83030214%2F00175037652%2F1898010101%2F0005.jp2/info.json',
?                                                                                                                                                 ++++++++++

                u'@type': u'oa:Annotation',
                u'motivation': u'sc:painting',
-               u'on': u'https://oni.example.com/images/tile/batch_curiv_ahwahnee_ver01%2Fdata%2Fsn83030214%2F00175037652%2F1898010101%2F0005.jp2',
                u'rendering': [{u'@id': u'https://oni.example.com/lccn/sn83030214/1898-01-01/ed-1/seq-1.pdf',
                                u'format': u'application/pdf'},
                               {u'@id': u'https://oni.example.com/lccn/sn83030214/1898-01-01/ed-1/seq-1.jp2',
                                u'format': u'image/jp2'},
                               {u'@id': u'https://oni.example.com/lccn/sn83030214/1898-01-01/ed-1/seq-1/',
                                u'format': u'text/html'}],
-               u'resource': {u'@id': u'https://oni.example.com/images/tile/batch_curiv_ahwahnee_ver01%2Fdata%2Fsn83030214%2F00175037652%2F1898010101%2F0005.jp2',
+               u'resource': {u'@id': u'https://oni.example.com/images/tile/batch_curiv_ahwahnee_ver01%2Fdata%2Fsn83030214%2F00175037652%2F1898010101%2F0005.jp2/info.json',
?                                                                                                                                                               ++++++++++

                              u'@type': u'dctypes:Image',
                              u'format': u'image/jpeg',
                              u'height': 8677,
                              u'service': {u'@context': u'http://iiif.io/api/image/2/context.json',
-                                          u'@id': u'https://oni.example.com/images/tile/batch_curiv_ahwahnee_ver01%2Fdata%2Fsn83030214%2F00175037652%2F1898010101%2F0005.jp2',
+                                          u'@id': u'https://oni.example.com/images/tile/batch_curiv_ahwahnee_ver01%2Fdata%2Fsn83030214%2F00175037652%2F1898010101%2F0005.jp2/info.json',
?                                                                                                                                                                            ++++++++++

                                           u'profile': u'http://iiif.io/api/image/2/level0.json'},
                              u'width': 6394},
                u'seeAlso': [{u'@id': u'https://oni.example.com/lccn/sn83030214/1898-01-01/ed-1/seq-1/ocr.xml',
                              u'format': u'text/xml'}]}],
   u'label': u'1',
   u'thumbnail': u'https://oni.example.com/images/resize/batch_curiv_ahwahnee_ver01%2Fdata%2Fsn83030214%2F00175037652%2F1898010101%2F0005.jp2/full/240,/0/default.jpg',
   u'width': 6394}

----------------------------------------------------------------------
Ran 61 tests in 7.791s

FAILED (failures=2)
```

**Comment by jduss4** [comment]
Some of it might just be spacing / line returns, but the `info.json` stuff otherwise sticks out as being different between the two

**Comment by jechols** [comment]
Thanks.   Though now I'm even more confused.  I'll have to look into the other IIIF APIs as well as the actual IIIF code we've got implemented.  The output looks wrong to me in more ways than just what's failing.  None of those images are of type `image/jpeg`, for instance - they should be `image/jp2`.  And the IIIF server's compliance level is reported as 0, but ONI shouldn't actually make that claim - RAIS, for instance, complies with level 2 of the API, but ONI wouldn't know that - that's the point of having a separate IIIF image server: it can be whatever server you want.
