### ISSUE TITLE
DatabaseError when loading batch_dlc_jamaica_ver01

### ISSUE THREAD

**Issue by edsu** [open-oni/open-oni#58]
I get this stack trace when loading batch_dlc_jamaica_ver01 into my dockerized instance of open-oni:

```
zen:~ ed$ docker exec -it open-oni-dev /load_batch.sh batch_dlc_jamaica_ver01
INFO:root:loading batch at /opt/openoni/data/batches/batch_dlc_jamaica_ver01
INFO:openoni.core.batch_loader:loading batch: batch_dlc_jamaica_ver01
INFO:root:attempting to load marc record from http://chroniclingamerica.loc.gov/lccn/sn83030214/marc.xml
INFO:openoni.core.title_loader:loading titles from: http://chroniclingamerica.loc.gov/lccn/sn83030214/marc.xml
INFO:openoni.core.management.commands.load_titles:indexing new titles
INFO:rdflib:version: 3.2.3
INFO:openoni.core.views.image:NativeImage backend '%s' not available.
INFO:openoni.core.views.image:NativeImage backend '%s' not available.
INFO:openoni.core.views.image:Using NativeImage backend 'graphicsmagick'
INFO:openoni.core.batch_loader:Assigned page sequence: 1
INFO:openoni.core.batch_loader:Saving page. issue date: 1903-05-01 00:00:00, page sequence: 1
ERROR:openoni.core.batch_loader:unable to load batch: (1366, "Incorrect string value: '\\xE2\\x96\\xA0 to...' for column 'text' at row 1")
ERROR:openoni.core.batch_loader:(1366, "Incorrect string value: '\\xE2\\x96\\xA0 to...' for column 'text' at row 1")
Traceback (most recent call last):
  File "/opt/openoni/core/batch_loader.py", line 165, in load_batch
    issue = self._load_issue(mets_url)
  File "/opt/openoni/core/batch_loader.py", line 284, in _load_issue
    page = self._load_page(doc, page_div, issue)
  File "/opt/openoni/core/batch_loader.py", line 406, in _load_page
    self.process_ocr(page)
  File "/opt/openoni/core/batch_loader.py", line 436, in process_ocr
    text=text)
  File "/opt/openoni/ENV/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 533, in create
    return super(RelatedManager, self.db_manager(db)).create(**kwargs)
  File "/opt/openoni/ENV/local/lib/python2.7/site-packages/django/db/models/manager.py", line 149, in create
    return self.get_query_set().create(**kwargs)
  File "/opt/openoni/ENV/local/lib/python2.7/site-packages/django/db/models/query.py", line 416, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/openoni/ENV/local/lib/python2.7/site-packages/django/db/models/base.py", line 546, in save
    force_update=force_update, update_fields=update_fields)
  File "/opt/openoni/ENV/local/lib/python2.7/site-packages/django/db/models/base.py", line 650, in save_base
    result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)
  File "/opt/openoni/ENV/local/lib/python2.7/site-packages/django/db/models/manager.py", line 215, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/opt/openoni/ENV/local/lib/python2.7/site-packages/django/db/models/query.py", line 1675, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/opt/openoni/ENV/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 937, in execute_sql
    cursor.execute(sql, params)
  File "/opt/openoni/ENV/local/lib/python2.7/site-packages/django/db/backends/util.py", line 41, in execute
    return self.cursor.execute(sql, params)
  File "/opt/openoni/ENV/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 128, in execute
    six.reraise(utils.DatabaseError, utils.DatabaseError(*tuple(e.args)), sys.exc_info()[2])
  File "/opt/openoni/ENV/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 120, in execute
    return self.cursor.execute(query, args)
  File "/opt/openoni/ENV/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/opt/openoni/ENV/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
DatabaseError: (1366, "Incorrect string value: '\\xE2\\x96\\xA0 to...' for column 'text' at row 1")
WARNING:root:no OcrDump to delete for batch_dlc_jamaica_ver01 (Library of Congress, Washington, DC)
ERROR:openoni.core.management.commands.load_batch:unable to load batch: (1366, "Incorrect string value: '\\xE2\\x96\\xA0 to...' for column 'text' at row 1")
```

Does anyone else see this?

**Comment by edsu** [comment]
It looks like perhaps [this call in dev.sh](https://github.com/open-oni/docker-open-oni/blob/master/dev.sh#L23) to set the default character set didn't work since I don't have a mysql command line client locally. I tried setting it after the database schema had been set up, but I still get the same errors. Perhaps changing the database default doesn't affect the existing openoni database though.
